homeassistant:
  customize:
    package.node_anchors:
      Sensore Finestra: &sensore_finestra binary_sensor.finestra_studio_contact
      Valvola: &valvola climate.valvola_studio

################################################################################
##                  Recorder
################################################
recorder:
  include:
    entities:
      - sensor.valvola_studio_trv
      - sensor.studio_temperatura
      - sensor.studio_umidita

################################################################################
##                  input_text
################################################
input_text:
  apertura_finestra_studio:
    name: Cambio stato finestra Studio
  counter_finestra_studio:
    name: Cambio stato counter finestra Studio

################################################################################
##                  input_boolean
################################################
input_boolean:
  valvola_studio_notifica_vocale_finestra_aperta:
    name: Valvola studio Avviso vocale
    icon: mdi:circle-slice-8
  valvola_studio_notifica_true_temperature:
    name: Valvola studio Avviso differenza True Temperature
    icon: mdi:thermometer-lines

##############################################################################
##                  Input Number
################################################
input_number:
  valvola_studio_ritardo_controllo_finestra_aperta:
    name: Ritardo spegnimento
    icon: mdi:timelapse
    unit_of_measurement: Min
    min: 1
    max: 30
    step: 1

  valvola_studio_ritardo_notifica_finestra_aperta:
    name: Ritardo Notifica
    icon: mdi:message-text-clock-outline
    unit_of_measurement: Min
    initial: 10
    min: 5
    max: 120
    step: 5

  valvola_studio_avviso_finestra_lasciata_aperta:
    name: Ritardo Notifica finestra lasciata aperta
    icon: mdi:account-voice
    unit_of_measurement: Min
    initial: 30
    min: 5
    max: 240
    step: 5

################################################################################
##                  Counter
################################################
counter:
  finestra_studio:
    initial: 0
    step: 1
    icon: mdi:counter
    restore: true

################################################################################
##                  Meter
################################################
utility_meter:
  meter_valvola_studio_anno:
    source: sensor.tempo_valvola_studio
    cycle: yearly
    unique_id: meter_valvola_studio_anno
  meter_valvola_studio_mese:
    source: sensor.tempo_valvola_studio
    cycle: monthly
    unique_id: meter_valvola_studio_mese
  meter_valvola_studio_oggi:
    source: sensor.tempo_valvola_studio
    cycle: daily
    unique_id: meter_valvola_studio_oggi

################################################################################
##                  Binary Sensor
################################################
template:
  - binary_sensor:
      - name: Valvola Studio
        icon: mdi:circle-double
        state: "{{ state_attr('climate.valvola_studio' ,'hvac_action') == 'heating' }}"

  ################################################################################
  ##                  Sensor
  ################################################
  - sensor:
      - name: Stato Valvola Studio
        unique_id: stato_valvola_studio
        state: >-
          {{ state_attr('climate.valvola_studio','preset_mode') }}

      - name: "Tempo valvola Studio"
        unique_id: tempo_valvola_studio
        icon: mdi:history
        state: >-
          {% from 'history_stats_custom.jinja' import time_on %}
          {{ time_on('binary_sensor.valvola_studio') }}
        attributes:
          Durata: >
            {%if is_state('binary_sensor.valvola_studio', 'on') and (as_timestamp(states.binary_sensor.valvola_studio.last_changed)) <= as_timestamp(now())%}
              {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.valvola_studio.last_changed)) | timestamp_custom('%H:%M', false)) }}
            {% else %}
              0
            {% endif %}
          Oggi: >
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_valvola_studio_oggi')) }}
          Mese: >-
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_valvola_studio_mese')) }}
          Anno: >-
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_valvola_studio_anno')) }}

      - name: "Valvola studio trv"
        unique_id: valvola_studio_trv
        device_class: power_factor
        unit_of_measurement: "%"
        state: >
          {% if states('sensor.studio_riscaldamento') != 'unavailable' and states('sensor.studio_riscaldamento') != 'unknown' %}
            {{ states('sensor.studio_riscaldamento') }}
          {% else %}
            Verifica
          {% endif %}

      - name: "Last change finestra studio"
        unique_id: last_change_finestra_studio
        state: >-
          {%- set time = (as_timestamp(now()) - as_timestamp(states.binary_sensor.finestra_studio_contact.last_changed)) - 3600 | int  %}
          {{'Poco fa' if time | timestamp_custom('%M') | int < 1 else time | timestamp_custom('%H:%M', true) }}

      - name: "Last change finestra studio info"
        unique_id: last_change_finestra_studio_info
        state: >
          {% set sensor_date = states('input_text.apertura_finestra_studio')|int | timestamp_custom('%d/%m/%Y',true) %}
          {% if sensor_date == now().strftime('%d/%m/%Y') %}
            Oggi alle {{states('input_text.apertura_finestra_studio')|int | timestamp_custom('%H:%M',true)}}
          {% elif sensor_date == (now() - timedelta(days=1)).strftime('%d/%m/%Y') %}
            Ieri alle {{states('input_text.apertura_finestra_studio')|int | timestamp_custom('%H:%M',true)}}
          {% else %}
            Il {{ states('input_text.apertura_finestra_studio')|int | timestamp_custom('%d/%m/%Y') }} alle {{ states('input_text.apertura_finestra_studio')|int | timestamp_custom('%H:%M') }}
          {% endif %}
        attributes:
          Aperture: "{{ states('counter.finestra_studio')|int }}"

      - name: "Ricircolo aria studio"
        unique_id: ricircolo_aria_studio
        state: >-
          {% set ts = states('input_text.counter_finestra_studio') %}
          {% if ts not in ['unknown',''] %}
            {% set diff_min = ((as_timestamp(now()) - ts | float) / 60) | int %}

            {% if diff_min < 240 %}           {# meno di 4 ore #}
              Ok
            {% elif diff_min < 360 %}         {# 4–6 ore #}
              Medio
            {% elif diff_min < 480 %}         {# 6–8 ore #}
              Grave
            {% else %}
              Urgente
            {% endif %}
          {% else %}
            Attesa
          {% endif %}

        attributes:
          tempo: >-
            {% if is_state('binary_sensor.finestra_studio_contact', 'on') %}
              00:00
            {% else %}
              {% set ts = states('input_text.counter_finestra_studio') %}
              {% if ts not in ['unknown',''] %}
                {% set diff_sec = as_timestamp(now()) - ts | float %}
                {% set hours = (diff_sec // 3600) | int %}
                {% set minutes = ((diff_sec % 3600) // 60) | int %}
                {{ "%02d:%02d" | format(hours, minutes) }}
              {% else %}
                00:00
              {% endif %}
            {% endif %}
        icon: mdi:cached


      - name: "Valvola Studio True Temperature"
        unique_id: valvola_studio_true_temperature
        state: >
          {{(state_attr('climate.valvola_studio','current_temperature') |float(0) ) - (states('sensor.temperatura_studio') |float(0) ) |int}}

################################################################################
##                  AUTOMATION
###################################################
automation:
  - alias: "Conteggio apertura finestra studio"
    id: conteggio_apertura_finestra_studio
    mode: parallel
    initial_state: true
    triggers:
      - trigger: state
        id: "conteggio"
        entity_id: *sensore_finestra
        from: "off"
        to: "on"
        for:
          minutes: 3

      - trigger: time
        at: "05:00:00"
        id: "reset"
    actions:
      - choose:
          - conditions: # VARIABILE
              - alias: "VARIABILE"
                condition: trigger
                id: "conteggio"
            sequence:
              - action: input_text.set_value
                target:
                  entity_id: input_text.apertura_finestra_studio
                data:
                  value: "{{ as_timestamp(now()) | int }}"

              - action: counter.increment
                target:
                  entity_id: counter.finestra_studio
              - action: input_text.set_value
                target:
                  entity_id: input_text.counter_finestra_studio
                data:
                  value: "{{ as_timestamp(now()) | int }}"

          - conditions: # RESET
              - alias: "RESET"
                condition: trigger
                id: "reset"
            sequence:
              - action: counter.reset
                target:
                  entity_id: counter.finestra_studio

  - alias: "Valvola studio gestione finestra"
    id: valvola_studio_gestione_finestra
    initial_state: true
    mode: parallel
    triggers:
      - trigger: state #FINESTRA APERTA
        id: "chiusura"
        entity_id: *sensore_finestra
        from: "off"
        to: "on"
        for:
          minutes: "{{ states('input_number.valvola_studio_ritardo_controllo_finestra_aperta')|int(0) }}"

      - trigger: state #FINESTRA CHIUSA
        id: "apertura"
        entity_id: *sensore_finestra
        from: "on"
        to: "off"
        for:
          seconds: 15

      - trigger: state # NOTIFICA
        id: "notifica"
        entity_id: *sensore_finestra
        from: "off"
        to: "on"
        for:
          minutes: "{{ states('input_number.valvola_studio_ritardo_notifica_finestra_aperta')|int(0) +1 }}"

      - trigger: state # NOTIFICA FINESTRA LASCIATA APERTA
        id: "finestra_aperta"
        entity_id: *sensore_finestra
        from: "off"
        to: "on"
        for:
          minutes: "{{ states('input_number.valvola_studio_avviso_finestra_lasciata_aperta')|int(0) }}"
    conditions:
      - condition: template
        value_template: "{{ state_attr('climate.valvola_studio', 'preset_mode') == 'home' }}"
    actions:
      - choose:
          - conditions: # CHIUSURA
              - alias: "CHIUSURA"
                condition: trigger
                id: "chiusura"
            sequence:
              - action: climate.turn_off
                target:
                  entity_id: *valvola

          - conditions: # APERTURA
              - alias: "APERTURA"
                condition: trigger
                id: "apertura"
              - condition: template
                value_template: "{{ state_attr('climate.valvola_studio', 'preset_mode') == 'home' }}"
            sequence:
              - action: climate.turn_on
                target:
                  entity_id: *valvola
              - action: climate.set_hvac_mode
                data:
                  hvac_mode: auto
                target:
                  entity_id: *valvola

          - conditions: # NOTIFICA
              - alias: "NOTIFICA"
                condition: trigger
                id: "notifica"
            sequence:
              - action: script.multinotify
                data:
                  notify_app: notify.famiglia
                  title: "Valvola Studio"
                  message: "Finestra dello studio aperta da {{states('sensor.last_change_finestra_studio')}}."
                  group: "valvola_studio"
                  tag: "valvola_studio_apertura"

          - conditions: # NOTIFICA FINESTRA LASCIATA APERTA
              - alias: "NOTIFICA FINESTRA LASCIATA APERTA"
                condition: trigger
                id: "finestra_aperta"
            sequence:
              - if:
                  - condition: state
                    entity_id: input_boolean.valvola_studio_notifica_vocale_finestra_aperta
                    state: "on"
                then:
                  - action: script.multinotify
                    data:
                      notify_app: notify.famiglia
                      title: "Valvola Studio"
                      message: >
                        {% set tempo = states('input_number.valvola_studio_avviso_finestra_lasciata_aperta') |int %}
                        {{["La finestra dello studio è ormai aperta da " ~ tempo ~ "minuti",
                            "Sono passati già " ~ tempo ~ " minuti da quando hai aperto la finestra dello studio!",
                            "Penso che " ~ tempo ~ " minuti possano bastare. Ora puoi chiudere la finestra dello studio",
                            "Hey che ne dici di chiudere la finestra dello studio?  è aperta da " ~ tempo ~ " minuti",
                            "Forse hai dimenticato di aver aperto al finestra dello studio. L'hai aperta " ~ tempo ~ " minuti fa!",
                            "Hey" ~ tempo ~ " minuti sono passati. Che ne dici di chiudere la finestra dello studio? "] | random}}
                      alexa_target: media_player.in_casa
                      alexa_force: true
                      group: "valvola_studio"
                      tag: "valvola_studio_apertura"

              - action: script.multinotify
                data:
                  notify_app: notify.famiglia
                  title: "Valvola Studio"
                  message: >
                    {% set tempo = states('input_number.valvola_studio_avviso_finestra_lasciata_aperta') |int %}
                    {{["La finestra dello studio è ormai aperta da " ~ tempo ~ "minuti",
                        "Sono passati già " ~ tempo ~ " minuti da quando hai aperto la finestra dello studio!",
                        "Penso che " ~ tempo ~ " minuti possano bastare. Ora puoi chiudere la finestra dello studio",
                        "Hey che ne dici di chiudere la finestra dello studio?  è aperta da " ~ tempo ~ " minuti",
                        "Forse hai dimenticato di aver aperto al finestra dello studio. L'hai aperta " ~ tempo ~ " minuti fa!",
                        "Hey" ~ tempo ~ " minuti sono passati. Che ne dici di chiudere la finestra dello studio? "] | random}}
                  tag: "valvola_studio_apertura"
                  group: "valvola_studio"

  - alias: "Avviso disconnessione valvola studio"
    id: avviso_disconnessione_valvola_studio
    initial_state: true
    triggers:
      - trigger: state
        entity_id: *valvola
        to: "unavailable"
    actions:
      - action: script.multinotify
        data:
          notify_app: !secret notifiche_francesco
          title: "Valvola Studio"
          message: Valvola studio disconnessa.
          group: "valvola_studio"

  - alias: "Avviso True Temperature valvola studio"
    id: avviso_true_temperature_valvola_studio
    initial_state: true
    triggers:
      - trigger: numeric_state
        entity_id: sensor.valvola_studio_true_temperature
        above: 1.5
        for:
          minutes: 60
    conditions:
      - condition: state
        entity_id: input_boolean.valvola_studio_notifica_true_temperature
        state: "on"
    actions:
      - action: script.multinotify
        data:
          notify_app: !secret notifiche_francesco
          title: "Valvola Studio"
          message: >
            L'offset dello valvola è di {{states('sensor.valvola_studio_true_temperature')}}°
            La temperatura dello valvola è {{(state_attr('climate.valvola_studio','current_temperature') |float)}}°, mentre la temperatura ambientiale
            risulta {{(states('sensor.temperatura_studio') |float) }}°
          group: "valvola_studio"
          tag: "true_temperature"

  - alias: "Notifica Batteria scarica valvola studio"
    id: notifica_batteria_scarica_valvola_studio
    initial_state: true
    triggers:
      - trigger: template
        value_template: >-
          {{is_state('binary_sensor.valvola_studio_batteria', 'on') }}
        for:
          minutes: 5
    actions: # SERVIZIO DI NOTIFICA
      - action: script.multinotify
        data:
          notify_app: !secret notifiche_francesco
          title: "Attenzione"
          message: Batteria Valvola Studio scarica

  - alias: "Avviso ricambio aria valvola studio"
    id: avviso_ricambio_aria_valvola_studio
    initial_state: true
    triggers:
      - trigger: state
        id: "1_ora"
        entity_id: sensor.ricircolo_aria_studio
        to: "Urgente"
        for:
          hours: 1
      - trigger: state
        id: "2_ora"
        entity_id: sensor.ricircolo_aria_studio
        to: "Urgente"
        for:
          hours: 2
    conditions:
      - condition: state
        entity_id: input_boolean.avvisi_generale_ricircolo_aria
        state: "on"
      - condition: time
        after: "11:00:00"
        before: "22:30:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    actions:
      - choose:
          - conditions: # 1 ORA
              - alias: "CHIUSURA"
                condition: trigger
                id: "1_ora"
            sequence:
              - action: script.multinotify
                data:
                  notify_app: notify.famiglia
                  title: "Ricambio Aria"
                  message: "In studio la finestra non viene aperta da 9 ore"
                  group: "valvola_studio"
                  tag: "valvola_studio_apertura"

          - conditions: # 2 ORE
              - alias: "CHIUSURA"
                condition: trigger
                id: "2_ora"
            sequence:
              - action: script.multinotify
                data:
                  title: "Valvola studio"
                  message: >
                    {{["La finestra dello studio non viene aperta da 10 ore",
                        "Sono passate più di 10 ore da quando è stata cambiata l'aria in studio",
                        "Potresti cambiare l'aria in studio? Non viene fatto da 10 ore",
                        "Forse hai dimenticato di aprire in studio, sono passate 10 ore da l'ultima volta"] | random}}
                  alexa_target: media_player.in_casa
                  alexa_force: true

  - alias: "Pulizia notifiche valvola studio"
    id: pulizia_notifiche_valvola_studio
    triggers:
      - trigger: state
        entity_id: *sensore_finestra
        from: "on"
        to: "off"
    actions:
      - action: notify.mobile_app_francesco
        data:
          message: "clear_notification"
          data:
            tag: "valvola_studio_apertura"
      - action: notify.mobile_app_iphone_di_simona
        data:
          message: "clear_notification"
          data:
            tag: "valvola_studio_apertura"
