################################################################################
##                  Meter
################################################
utility_meter:
  meter_termostato_anno:
    unique_id: durata_riscaldamento_generale_anno
    source: sensor.durata_riscaldamento_generale
    cycle: yearly
  meter_termostato_mese:
    unique_id: durata_riscaldamento_generale_mese
    source: sensor.durata_riscaldamento_generale
    cycle: monthly
  meter_termostato_oggi:
    unique_id: durata_riscaldamento_generale_oggi
    source: sensor.durata_riscaldamento_generale
    cycle: daily

################################################################################
##                  input_boolean
################################################
input_boolean:
  avvisi_generale_ricircolo_aria:
    name: Avvisi Ricircola aria
    icon: mdi:volume-source
  riscaldamento_modo_ospiti:
    name: Modalità ospiti
    icon: mdi:account-group

################################################################################
##                  Timer
###################################################
timer:
  riscaldamento_modo_ospiti:
    duration: "00:30:00"

template:
  ################################################################################
  ##                  Sensor
  ################################################
  - binary_sensor:
      - name: "Riscaldamento Generale"
        state: >
          {{ ((states.climate)
              | selectattr('entity_id','search','valvola')
              | selectattr('attributes.hvac_action', 'eq', 'heating')
              | rejectattr('entity_id','search','homekit')
              | map(attribute='entity_id')
              | list
              | count > 0)
          }}

  - sensor:
      - name: "Durata riscaldamento generale"
        unique_id: durata_riscaldamento_generale
        state: >-
          {% if is_state('binary_sensor.riscaldamento_generale', 'on') %}
            {% set delta = as_timestamp(now()) - as_timestamp(states.binary_sensor.riscaldamento_generale.last_changed) %}
            {{ (delta // 3600)|int }}h {{ ((delta % 3600) // 60)|int }}m
          {% else %}
            0h 0m
          {% endif %}
        attributes:
          Oggi: >
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_termostato_oggi')) }}
          Mese: >-
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_termostato_mese')) }}
          Anno: >-
            {% from 'history_stats.jinja' import history %}
            {{ history(states('sensor.meter_termostato_anno')) }}

      - name: "Numero Valvole Accese"
        unique_id: numero_valvole_accese
        state: >-
          {{ ((states.climate)
            | selectattr('entity_id','search','valvola')
            | selectattr('attributes.hvac_action', 'eq', 'heating')
            | rejectattr('entity_id','search','homekit')
            | map(attribute='entity_id')
            | list
            | count ) }}

################################################################################
##                  Script
###################################################
script:
  temperatura_up:
    sequence:
      - action: climate.set_temperature
        data:
          temperature: >
            {{ state_attr(climate_id, 'temperature') + 0.5 | float }}
        target:
          entity_id: "{{ climate_id }}"

  temperatura_down:
    sequence:
      - action: climate.set_temperature
        data:
          temperature: >
            {{ state_attr(climate_id, 'temperature') - 0.5 | float }}
        target:
          entity_id: "{{ climate_id }}"

  away:
    sequence:
      - action: climate.set_preset_mode
        data:
          preset_mode: "away"
        target:
          entity_id: >
            {{(states.climate)
              | selectattr('entity_id','search','valvola')
              | map(attribute='entity_id')
              | list
              | first }}

      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.riscaldamenti_accesi


  preset_mode:
    sequence:
      - action: climate.set_preset_mode
        data:
          preset_mode: "home"
        target:
          entity_id: >
            {{(states.climate)
              | selectattr('entity_id','search','valvola')
              | map(attribute='entity_id')
              | list
              | first }}

      - action: automation.turn_off
        target:
          entity_id: automation.avviso_riscaldamento_acceso

  power_off_valvole:
    sequence:
      - action: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: >-
            {{ (states.climate)
                | selectattr('entity_id','search','valvola')
                | map(attribute='entity_id')
                | list }}

  riscaldamento_modo_ospiti:
    sequence:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.riscaldamento_modo_ospiti

      - action: climate.set_temperature
        data:
          temperature: 20.5
          hvac_mode: auto
        target:
          entity_id:
            - climate.valvola_soggiorno
            - climate.valvola_cucina
      - action: climate.set_temperature
        data:
          temperature: 19.5
          hvac_mode: auto
        target:
          entity_id:
            - climate.valvola_cameretta
            - climate.valvola_studio

      - action: timer.cancel
        target:
          entity_id: timer.riscaldamento_modo_ospiti
      - action: timer.start
        target:
          entity_id: timer.riscaldamento_modo_ospiti

  riscaldamento_modo_ospiti_off:
    sequence:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.riscaldamento_modo_ospiti
      - action: timer.cancel
        target:
          entity_id: timer.riscaldamento_modo_ospiti
      - action: climate.set_hvac_mode
        data:
          hvac_mode: auto
        target:
          entity_id: >-
            {{ (states.climate)
                | selectattr('entity_id','search','valvola')
                | map(attribute='entity_id')
                | list }}

###############################################################################
#                  AUTOMATION
###################################################
automation:
  - alias: "Riscaldamento modalità ospiti"
    id: "riscaldamento_modalità_ospiti"
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.riscaldamento_modo_ospiti
    actions:
      - choose:
          - conditions:
              - alias: "Ripeti"
                condition: state
                entity_id: input_boolean.riscaldamento_modo_ospiti
                state: "on"
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.riscaldamento_modo_ospiti
      - choose:
          - conditions:
              - alias: "Ripeti"
                condition: state
                entity_id: input_boolean.riscaldamento_modo_ospiti
                state: "off"
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.riscaldamento_modo_ospiti_off

  - alias: "Riscaldamento modalità ospiti_off"
    id: "riscaldamento_modalità_ospiti_off"
    triggers:
      - trigger: time
        at: "00:30:00"
    actions:
      - action: script.turn_on
        target:
          entity_id: script.riscaldamento_modo_ospiti_off
